### ISSUE TITLE
Feature request: Use `sample name` in `gen_kmer.py` output

### ISSUE THREAD

**Issue by susheelbhanu** [ziyewang/MetaBinner#13]
Hi, 

I was looking into running `MetaBinner` on multiple samples via snakemake. And all my sample assembly files are stored in the same directory. While I could move them to individual directories, it may be efficient to either allow naming the outputs of `gen_kmer.py` or alternatively use the sample name in the output.

For example, in line 19 of your [Filter_tooshort.py](https://github.com/ziyewang/MetaBinner/blob/master/scripts/Filter_tooshort.py) script, you have the following line, where the sample name is used as a prefix:
```
output_file = os.path.splitext(input_file)[0] + '_' + str(k) + '.fa'
```

Could you please add something similar to line 63 of the [gen_kmer.py](https://github.com/ziyewang/MetaBinner/blob/master/scripts/gen_kmer.py) script. Example below:
```
 outfile = os.path.join(os.path.dirname(fasta_file), os.path.splitext(fasta_file)[0] + '_kmer_' + str(kmer_len) + '_f' + str(length_threshold) + '.csv')
```

Thank you,
Susheel

**Comment by ziyewang** [comment]
Hi, Susheel

Thanks for your suggestion. I have added the sample name in gen_kmer.py. 

Best,
Ziye

**Comment by susheelbhanu** [comment]
Thanks a lot @ziyewang!
