### ISSUE TITLE
Question with the metabinner_result.tsv

### ISSUE THREAD

**Issue by B-1991-ing** [ziyewang/MetaBinner#15]
Dear MetaBinner support team,

I got my metabinner_result.tsv already (#The file "metabinner_result.tsv" in the "${output_dir}/metabinner_res" is the final output.)
[metabinner_result.tsv.txt](https://github.com/ziyewang/MetaBinner/files/8548616/metabinner_result.tsv.txt)

My metabinner_result.tsv only has two columns as shown below. But, if I want to see the completeness and contamination of the assemble bins or MAGs, which file should I check? I want to check how many bins with >70% completeness and <5% contamination?

<img width="1342" alt="Screenshot 2022-04-23 at 23 06 52" src="https://user-images.githubusercontent.com/54441633/164945982-3d9c2ac1-392e-4a8c-b142-1d11fd58d506.png">

Best,

Bing

**Comment by ziyewang** [comment]
Hi, Bing

Please find the assemble bins in: ${output_dir}/metabinner_res/ensemble_res/greedy_cont_weight_3_mincomp_50.0_maxcont_15.0_bins/ensemble_3logtrans/addrefined2and3comps/greedy_cont_weight_3_mincomp_50.0_maxcont_15.0_bins

Best,
Ziye

**Comment by B-1991-ing** [comment]
Hi Ziye,

Thank you very much for your reply.

I found the bin files with minimal completeness > 50% and maximal contamination < 15%, as you suggested. So, we could directly see the exact completeness and contamination of each bin as shown below? As I want to compare the performance of four binners - MetaBAT2, MaxiBin2, MetaBinner, Semibin.

<img width="1196" alt="Screenshot 2022-04-24 at 12 21 08" src="https://user-images.githubusercontent.com/54441633/164971869-d5bfc1bb-1ca8-4a91-9f00-228194492395.png">
 
Best,

Bing

**Comment by B-1991-ing** [comment]
Hi Ziye,

I found one similar file - ${output_dir}/metabinner_res/ensemble_res/greedy_cont_weight_3_mincomp_50.0_maxcont_15.0_bins/ensemble_3logtrans/addrefined2and3comps/**bin_info_initial.tsv** as shown below. Can I use this file to extract and compare the completeness and contamination of the final assemble bins with other binners?

<img width="1345" alt="Screenshot 2022-04-24 at 12 40 45" src="https://user-images.githubusercontent.com/54441633/164972543-24ec03a4-b8bf-4008-9125-6a5f617fa1af.png">

Best,

Bing

**Comment by ziyewang** [comment]
Hi, Bing,

Sorry, you cannot use values in the "bin_info_initial.tsv" file for comparison. The completeness and contamination values used in our program are estimated using a simplified version of CheckM. We don't provide the evaluation results, because the evaluation results may be different while using different versions of CheckM. If you would like to compare the performance of MetaBinner using the evaluation statistic results from MetaWRAP, you can run MetaWRAP on the assembled bins of MetaBinner. I hope my understanding is correct.

Best,
Ziye

**Comment by B-1991-ing** [comment]
Hi Ziye, 

Thank you very much for your quick reply.

I get it now. Because I already have compared the performance of MetaBAT2, MaxiBin2 and CONCOCT using the evaluation statistic results from MetaWRAP bin refinement as shown below (**Previous pipeline**).

![image](https://user-images.githubusercontent.com/54441633/164973222-f0a3a496-c70d-459d-ba61-6884fae6c761.png)


Thank you very much.

Best,

Bing
