### ISSUE TITLE
Run metabinner with designated BAM

### ISSUE THREAD

**Issue by CongLiu37** [ziyewang/MetaBinner#17]
Hi!

Thank you for the useful tool. I would like to suggest add an option for BAM for gen_coverage_file.sh, to make it accept designated BAM file. The help manual of gen_coverage_file.sh says "If the output already has the .bam alignments files from previous runs, the module will skip re-aligning the reads", but for me it is not clear that how such BAM files are named, and I do not want to put BAM and binning into the same directory.

Sincerely,

Cong

**Comment by ziyewang** [comment]
Hello Cong,

I have added an option "-b" to run gen_coverage_file.sh with the designated BAM files. The output directory when running gen_coverage_file.sh refers to the directory where the bam file and the generated coverage profile are saved, which can be different from MetaBinner's directory. BAM files should be suffixed with ".bam". For example, "Reads.1_1.fastq Reads.1_2.fastq->Reads.1.bam". Sorry for not replying in time.

Best wishes,
Ziye
