### ISSUE TITLE
Warning message in log files

### ISSUE THREAD

**Issue by B-1991-ing** [ziyewang/MetaBinner#18]
Dear MetaBinner support team,

I always got same warning message in my log files. What should I do to avoid it?

Screenshot of warning message:
<img width="1360" alt="Screenshot 2022-06-19 at 19 02 20" src="https://user-images.githubusercontent.com/54441633/174492260-fc80660c-db68-4663-b8e8-0f715210cc66.png">

My job script:
[metabinner_25.sh.txt](https://github.com/ziyewang/MetaBinner/files/8935980/metabinner_25.sh.txt)

Best,

Bing

**Comment by ziyewang** [comment]
Hi, Bing,

The warning message does not affect running MetaBinner. We will consider making corresponding changes and testing in future versions.

Best,
Ziye

**Comment by B-1991-ing** [comment]
Hi Ziye,

Thank you very much for your reply and conformation.

Best,

Bing
