### ISSUE TITLE
something wrong in the script - Filter_tooshort.py

### ISSUE THREAD

**Issue by B-1991-ing** [ziyewang/MetaBinner#19]
Hi Ziye,

I ran the Filter_tooshort.py on my megabit assembled **final.contigs.fa**. I checked the generated **final.contigs_1000.fa**, no ">" before each sequence name there, so the gen_kmer.py generated **kmer_4_f1000.csv** is also empty. Maybe you need to have a check on the script - Filter_tooshort.py.

**Screenshot of the final.contigs_1000.fa**
<img width="1369" alt="Screenshot 2022-07-28 at 13 56 35" src="https://user-images.githubusercontent.com/54441633/181499208-da61c751-2964-4c95-b003-c2983ba121e1.png">

**Screenshot of the kmer_4_f1000.csv**
<img width="1076" alt="Screenshot 2022-07-28 at 13 57 47" src="https://user-images.githubusercontent.com/54441633/181499437-799e9695-db69-48d2-bb21-116effc9d4e0.png">

Best,

Bing

**Comment by ziyewang** [comment]
Hi, Bing

It seems that the latest version of this script works fine. 

Best, 
Ziye

**Comment by B-1991-ing** [comment]
Hi Ziye,

Maybe due to I am working with the **metabinner/1.4.2**, which is the not the newest version - 1.4.3.

I skipped this step now.

Thank you very much.

Best,

Bing
