### ISSUE TITLE
Got error: out of bounds for axis 0 while running Metabinner.py

### ISSUE THREAD

**Issue by dawnmy** [ziyewang/MetaBinner#2]
```shell
Traceback (most recent call last):
  File "/CAMI/docker/binners/MetaBinner/Metabinner.py", line 913, in <module>
    X_t, namelist, mapObj, X_cov_sr, X_com = gen_X(com_file, cov_file)
  File "/CAMI/docker/binners/MetaBinner/Metabinner.py", line 96, in gen_X
    compositMat = shuffled_compositMat[covIdxArr]
IndexError: index 94388951158496 is out of bounds for axis 0 with size 349831
```

BTW, there were only two coverage files produced by `run.sh` even I used the both short reads and long reads for computing coverage. But the example command line has two coverage files: `coverage_sr_new.tsv`, ` coverage_pb_new.tsv`. Did I get something wrong?

**Comment by ziyewang** [comment]
This situation happens when there are some contigs in the coverage file, but not in the com_file file. Please filter the contigs.
As for the following question, I didn't understand. Did you get two coverage files or one coverage file?

Best,
Ziye

**Comment by dawnmy** [comment]
Sorry for the typo. There were two coverage files namely `coverage_new.tsv`, and `coverage.tsv` produced by run.sh when I used the both short reads and long reads for computing coverage. But the example command line has coverage files: `coverage_sr_new.tsv`, `coverage_pb_new.tsv`. Did I get something wrong?

**Comment by dawnmy** [comment]
The `coverage_new.tsv` contains both Pacbio and short reads but with different ID <img width="1051" alt="image" src="https://user-images.githubusercontent.com/497428/84594419-5da70680-ae52-11ea-8eca-937d2e387576.png">. For ten samples, Pacbio starts from 11, while short reads starts from 1. Can I used this as input file for option --coverage_profiles?

**Comment by ziyewang** [comment]
You can use them as the input file for the option, but you should use "coverage_new_f1000.tsv" as the input if your com_file only contains the contigs longer than 1000bp.  But I advise you to split the coverage file into the coverage file for long reads(coverage_pb) and the coverage for short reads (coverage_sr) as shown in "run.sh", " split_coverage.py". 
"""
#eg: ./run.sh 
/mnt/data4/wzy/preprocess/strmg_megahit_assembly/test_input/strmgCAMI2_short_read_pooled_megahit_assembly.fasta 1000 4
# ./run.sh fasta_file  contig_length_threshold kmer_number

input_dir=$(dirname $1)

# prpocess.sh $1s
python Filter_tooshort.py $1 $2
python join.py ${input_dir} $2
python gen_kmer.py $1 $2 $3
python split_coverage.py ${input_dir} $2
"""

Best,
Ziye

**Comment by dawnmy** [comment]
> You can use them as the input file for the option, but you should use "coverage_new_f1000.tsv" as the input if your com_file only contains the contigs longer than 1000bp. But I advise you to split the coverage file into the coverage file for long reads(coverage_pb) and the coverage for short reads (coverage_sr) as shown in "run.sh" and " split_coverage.py".
> 
> Best,
> Ziye

Thank you for your explain. Just realized that the `run.sh` did not work properly because package `Click` was missing. This was why I was not able to find the `coverage_sr_new.tsv`, `coverage_pb_new.tsv` files. Maybe `Click` should also be added into the conda env YAMl file.

**Comment by ziyewang** [comment]
Thanks for the kind reminder.
