### ISSUE TITLE
Two bugs to fix for preparing data

### ISSUE THREAD

**Issue by Hocnonsense** [ziyewang/MetaBinner#20]
1. in `gen_coverage_file.sh`, you forget to keep man selected minimum contig length, please check it.
2. in `gen_kmer.py`, you forget to separate filename and dirname, please check it.
   - https://github.com/ziyewang/MetaBinner/blob/12686167a8dda2fcf7269cc3dda1865269c02872/scripts/gen_kmer.py#L63

**Comment by ziyewang** [comment]
Thanks very much.

The bugs have been fixed.

Best,
Ziye

**Comment by Hocnonsense** [comment]
Thanks!
