### ISSUE TITLE
error in subscript of component_binning.py

### ISSUE THREAD

**Issue by Xchenkai2019** [ziyewang/MetaBinner#25]
主要问题：“File "./component_binning.py", line 406, in”参考如下截图。用的是您团队提供的测试数据和命令行：run_metabinner.sh -a final_contigs_f1k.fa -d coverage_profile_f1k.tsv -t 40 -k kmer_4_f1000.csv -p  /home/chenkai/miniconda3/envs/metabinner_env/bin/ -o metabinner.test
问题截图如下：
![image](https://github.com/ziyewang/MetaBinner/assets/54092076/ff578914-bd6e-4343-9bb3-b2d1f301f893)
谢谢

**Comment by ziyewang** [comment]
请问还有问题吗？如果仍需要解决的话，能否提供一下完整的报错信息？

谢谢

**Comment by Xchenkai2019** [comment]
谢谢回复，请问有新的更新吗？
软件安装参照您提供的conda 流程，运行命令 conda activate /home/chenkai/miniconda3/envs/metabinner_env/ 
run_metabinner.sh -a final_contigs_f1k.fa -d coverage_profile_f1k.tsv -t 40 -k kmer_4_f1000.csv -p /home/chenkai/miniconda3/envs/metabinner_env/bin/ -o metabinner.test
完整报错信息如下：
Traceback (most recent call last):
  File "./component_binning.py", line 406, in <module>
    handler = logging.FileHandler(args.log)
  File "/home/chenkai/miniconda3/envs/metabinner_env/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/chenkai/miniconda3/envs/metabinner_env/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/chenkai/miniconda3/envs/metabinner_env/bin/scripts/metabinner.test/metabinner_res/result.log'

**Comment by ziyewang** [comment]
你好，应该是因为代码会改变当前路径，所以请给输出-a -d -k -o输入绝对路径，例如 /home/chenkai/metabinner.test。

**Comment by Xchenkai2019** [comment]
添加绝对路径后成功运行，再次感谢！
