### ISSUE TITLE
make gen_coverage_file accept compressed files

### ISSUE THREAD

**Issue by Sanrrone** [ziyewang/MetaBinner#27]
Dears,
along with greeting you, the gen_coverage_file script to generate the coverages only accept .fastq sequences, but my files (which are more than 2000) are all compressed. in fq.gz format, How can make the script accept the compressed format?

thanks in advance!

**Comment by ziyewang** [comment]
Hi, 

Is the sequencing data pair-end, single-end or interleaved? If it's pair-end, the original code can be used directly by just modifying the input options. If not, I'll update the code to support compressed files.

"Options:
        -f              Forward read suffix for paired reads (default="_1.fastq")
	-r              Reverse read suffix for paired reads (default="_2.fastq")"

Best,
Ziye
