### ISSUE TITLE
Update ETA

### ISSUE THREAD

**Issue by GeoMicroSoares** [ziyewang/MetaBinner#3]
Hi there,
Congrats for the tool - I'm really interested in using this tool for a large metagenomics dataset that I pulled from NCBI. First question would be when are you planning to release the update? Second one would be - would you recommend running this tool on a dataset that includes unrelated samples?
Thanks in advance and all the best!

**Comment by ziyewang** [comment]
Hi,

Thanks. We would like to release the update in three days. We did not test its perfromance on unrelated samples, if you want to try it, we look forward to your response. By the way, we recommend running this tool on a dataset with more than five or ten samples, but it also supports single-sample dataset.
Please feel free to let us know if you have any questions.

Best,
Ziye

**Comment by GeoMicroSoares** [comment]
This is awesome - will wait for the update and try out the tool on the dataset. Many thanks and good luck for releasing the update!
