### ISSUE TITLE
How to set the tmp dir of metabinner?

### ISSUE THREAD

**Issue by quliping** [ziyewang/MetaBinner#33]
As the title, How to set the tmp dir of metabinner? I found that metabinner just ouput tmp files in the current dir. Thanks!

**Comment by ziyewang** [comment]
Hi,

You can try this method. Set an environment variable named TMPDIR and assign it the path of the folder you want to use as the temporary folder. For example: export TMPDIR=/path/to/custom/tmp/folder. And then run the MetaBinner.

Best,
Ziye

**Comment by quliping** [comment]
> Hi,
> 
> You can try this method. Set an environment variable named TMPDIR and assign it the path of the folder you want to use as the temporary folder. For example: export TMPDIR=/path/to/custom/tmp/folder. And then run the MetaBinner.
> 
> Best, Ziye

Thanks a lot!
