### ISSUE TITLE
Differences between SolidBin and MetaBinner

### ISSUE THREAD

**Issue by quliping** [ziyewang/MetaBinner#34]
MetaBinner is a good software for metagenomic binning analysis. In my work, I'm trying to find a best binning software. Therefore, I tested several binners. I found Ziye Wang is the author of both SolidBin and MetaBinner, and the workflows of these two softwares are very similar. My question is, what is the difference between these two software and which one is better?

By the way, the database of checkm is very old, is there any plan to replace checkm1 with checkm2? 

Sincerely，

Qu Liping

**Comment by ziyewang** [comment]
Hi,

Metabinner and SolidBin are similar in the way they estimate the number of bins. However, they differ significantly in their clustering methods. Metabinner is an ensemble method, whereas SolidBin is based on semi-supervised methods. SolidBin is not suitable for large-scale datasets. In most cases, Metabinner is the preferred choice. Thank you for the suggestion, but at the moment, there are no plans to replace CheckM1 with CheckM2.

Best,
Ziye

**Comment by quliping** [comment]
Thanks for your reply.
